### ISSUE TITLE
Question: link to jump to a specific page

### ISSUE THREAD

**Issue by zbouslikhin** [typst/pdf-writer#9]
Hello,

I am trying to create a link to jump to a specific page within the PDF. Is it something doable using pdf-writer?

**Comment by laurmaedje** [comment]
Yes, you can do this with pdf-writer. PDF implements links (both to URLs and pages of the document) as annotations. There is an example of how link annotations work in the [hello example](https://github.com/typst/pdf-writer/blob/main/examples/hello.rs). Now, to link to a page instead of an URL, you have to replace this
```rust
annotation
    .action()
    .action_type(ActionType::Uri)
    .uri(Str(b"https://www.rust-lang.org/"));
```
with something like this:
```rust
annotation
    .action()
    .action_type(ActionType::GoTo)
    .destination_direct()
    .page(target_page)
```
Here, `target_page` is the indirect reference id of the page you want to jump to. There are also [more options](https://docs.rs/pdf-writer/0.6.0/pdf_writer/writers/struct.Destination.html) for specifying an exact position on the page, zoom level etc.
